In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

1. Задание
- Вектор – это частный случай матрицы 1хN и Nх1. Повторите материал для векторов, уделяя особое внимание умножению A∙B.

In [41]:
a = np.arange(1, 6).reshape(1, 5)
b = a.reshape(5,1)
a, b, a.shape, b.shape

(array([[1, 2, 3, 4, 5]]),
 array([[1],
        [2],
        [3],
        [4],
        [5]]),
 (1, 5),
 (5, 1))

In [52]:
a + b

array([[ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10]])

In [46]:
a * 2, b * 2

(array([[ 2,  4,  6,  8, 10]]),
 array([[ 2],
        [ 4],
        [ 6],
        [ 8],
        [10]]))

In [43]:
a * b

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [53]:
a @ b

array([[55]])

In [47]:
a - b

array([[ 0,  1,  2,  3,  4],
       [-1,  0,  1,  2,  3],
       [-2, -1,  0,  1,  2],
       [-3, -2, -1,  0,  1],
       [-4, -3, -2, -1,  0]])

In [56]:
a, a.T

(array([[1, 2, 3, 4, 5]]),
 array([[1],
        [2],
        [3],
        [4],
        [5]]))

____

- Вычислите, по возможности не используя программирование: $(5E)^{-1}$ где Е – единичная матрица размера 5х5.

$ (5E)^{-1} = \frac{1}{5}E $  

In [13]:
A_5 = np.identity(5)*5
np.linalg.inv(A_5)

array([[ 0.2,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0.2,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0.2,  0. ,  0. ],
       [-0. , -0. , -0. ,  0.2, -0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0.2]])

___

2. Задание 

Вычислите определитель:  

$$ A = \left|\begin{array}{ccc}
1 & 2 & 3 \\
4 & 0 & 6 \\
7 & 8 & 9 
\end{array}\right|$$  

$ \det A = 1 \cdot \left|\begin{array}{cc}0 & 6 \\ 8 & 9 \end{array}\right| - 2 \cdot \left|\begin{array}{cc} 4 & 6 \\ 7 & 9 \end{array}\right| + 3 \cdot \left|\begin{array}{cc} 4 & 0 \\ 7 & 8 \end{array}\right| = -48-2 \cdot (36-42)+3 \cdot 32 = 60 $

In [27]:
A = np.array([[1, 2, 3],
              [4, 0, 6],
              [7, 8, 9]])
np.linalg.det(A)

59.999999999999986

___

3. Задание 

 Вычислите матрицу, обратную данной:  
 
$$ A =  \left|\begin{array}{ccc}
1 & 2 & 3 \\
4 & 0 & 6 \\
7 & 8 & 9 
\end{array}\right|$$

Обратную матрицу можно найти по формуле:  

$$ A^{-1} = \frac{1}{\det{A}}\cdot A_*^T $$  

где  

$ \det{A} $ - определитель матрицы А  
$ A_*^T $ - транспонированная матрица алгебраических дополнений матрицы А  

Определитель матрицы мы нашли в предыдущем задании:  

$\det{A} = 60 $  

Найдем матрицу миноров M:  

Минор для элемента $a_{0,0} = \left|\begin{array}{cc}0 & 6 \\ 8 & 9 \end{array}\right| = -48 $  

Аналогично для прочих элементов матрицы А  

$ M =  \left|\begin{array}{ccc}
-48 & -6 & 32 \\
-6 & -12 & -6 \\
12 & -6 & -8 
\end{array}\right|$  

Отсюда, матрица алгебраических дополнений будет выглядеть как  

$ A_* =  \left|\begin{array}{ccc}
-48 & 6 & 32 \\
6 & -12 & 6 \\
12 & 6 & -8 
\end{array}\right|$  

Транспонированная матрица алгебраических дополнений:  

$ A_*^T =  \left|\begin{array}{ccc}
-48 & 6 & 12 \\
6 & -12 & 6 \\
32 & 6 & -8 
\end{array}\right|$  

Следовательно,  

$ A^{-1} =  \frac{1}{60}\cdot\left|\begin{array}{ccc}
-48 & 6 & 12 \\
6 & -12 & 6 \\
32 & 6 & -8 
\end{array}\right|$ 

Проверим вычисления с помощью функции библиотеки numpy

In [26]:
A_m = np.array([[-48, 6, 32],
                [6, -12, 6],
                [12, 6, -8]])
A_m.T * 1/60

array([[-0.8       ,  0.1       ,  0.2       ],
       [ 0.1       , -0.2       ,  0.1       ],
       [ 0.53333333,  0.1       , -0.13333333]])

In [23]:
np.linalg.inv(A)

array([[-0.8       ,  0.1       ,  0.2       ],
       [ 0.1       , -0.2       ,  0.1       ],
       [ 0.53333333,  0.1       , -0.13333333]])

___

4. Задание 

 Приведите пример матрицы 4х4, ранг которой равен 1.

5. Задание 

Вычислите скалярное произведение двух векторов:  
(1, 5)  и  (2, 8)

Пусть  

У вектора $ \overrightarrow{a} $ координаты (1, 5)  
У вектора $ \overrightarrow{b} $ координаты (2, 8)  

Тогда, скалярное произведение  

$\overrightarrow{a}\cdot\overrightarrow{b} = 1 \cdot 2+5 \cdot 8 = 42$
___

6. Задание

Вычислите смешанное произведение трех векторов:
(1, 5, 0), (2, 8, 7) и (7, 1.5, 3) 


Вычислим смешанное произведение векторов как определитель матрицы, составленой из их координат  

$$ A = \left(\begin{array}{ccc}
1 & 5 & 0 \\
2 & 8 & 7 \\
7 & 1.5 & 3 
\end{array}\right)$$  

$ \det A = 1 \cdot \left|\begin{array}{cc}8 & 7 \\ 1.5 & 3 \end{array}\right| - 5 \cdot \left|\begin{array}{cc}2 & 7 \\ 7 & 3 \end{array}\right| = 228.5 $

In [2]:
A = np.array([[1, 5, 0],
              [2, 8, 7],
              [7, 1.5, 3]])
np.linalg.det(A)

228.49999999999986